pipeline{
    agent any

    environment{
        cluster = 'vproprod'
        service = 'vproappprodsvc'
    }

    stages{
        stage('Deploy to Prod ECS'){
            steps{
                script{
                    withAWS(credentials: 'awscreds', region: 'ap-southeast-1'){
                        sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                    }
                }
            }
        }
    }
}